#内置服务端口配置 timeout 1m 是一分钟
server:
  port: 8083
  servlet:
      session:
          timeout: 30m

#SpringBoot配置
spring:
    #devtools热部署配置
    devtools :
        restart:
            enabled: true
            additional-paths: src/main/java
            exclude: static/**,public/**,WEB-INF/**
    #数据源配置
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@192.168.1.121:1521:orcl
        username: alims
        password: alims
        # 初始化大小，最小，最大
        initialSize: 30
        minIdle: 30
        maxActive: 500
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
    #使用jsp配置
    mvc:
        thymeleaf:
            cache: false
            enabled: false
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    shiro:
        properties:
            authz: false
        session-id-cookie:
            http-only: false
            name: yui2-token
            maxAge: 2592000
        session-dao:
            #expire: 86400 选用globalSessionTimeout这个值
            session-prefix: yui2-sid
        session-mgr:
            globalSessionTimeout: 86400000
        shiro-db-realm:
            authentication-caching-enabled: false
            authorization-caching-enabled: false
            authentication-cache-name: yui2-cache-authc
            authorization-cache-name: yui2-cache-authz

    #solr
    data:
        solr:
            host: http://localhost:8080/solr/alims

    freemarker:
        allow-request-override: false
        allow-session-override: false
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        enabled: true
        expose-request-attributes: false
        expose-session-attributes: false
        expose-spring-macro-helpers: true
        prefer-file-system-access: true
        template-loader-path: classpath:/templates/*.ftl

#整合mybatis框架配置
mybatis:
    type-aliases-package: com.bazl.alims.model.po # 注意：对应实体类的路径
    mapper-locations: classpath:mapper/*.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mapper:
    mappers:
        - com.bazl.alims.dao.BaseMapper
    not-empty: false
    identity: oracle

#以下为文件上传配置路径
personImg: D:/img/person_img/
sampleImg: D:/img/sample_img/

#以下为上传ftp所需配置
ftpIp: 127.0.0.1
ftpPort: 21
ftpPersonImg: person_img
ftpSampleImg: sample_img
ftpUser: sss
ftpPassword: sssFTP
ftpTomcat: 8087

#以下为户籍接口地址
hjrkAdress: http://localhost:8098/HjrkWebService/ws/HjrkPersonInfoWebService?wsdl
xkAdress: http://localhost:8080/xkwebservice/xk/getCaseInfoXk.html?caseXkNo=

#shiro session失效时间  60000是一分钟  180000是半小时
shTime: 180000

#是否开启通知app 1=开启 0=关闭
Is_App_Inform : 0
Is_App_Url : 'http://20.1.11.52:5988/http/GA000Comm'